export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const PHONE_NUMBER_VERIFICATION_SUCCESS = "PHONE_NUMBER_VERIFICATION_SUCCESS";
export const SMS_CODE_VERIFICATION_SUCCESS = "SMS_CODE_VERIFICATION_SUCCESS";
export const SIGNUP_VERIFICATION_SUCCESS = "SIGNUP_VERIFICATION_SUCCESS";